'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, Calculator, Check, ChevronRight, ClipboardList, FileText, Search, ShoppingCart, Truck, ShieldCheck, RotateCcw, CreditCard, TrendingUp, Minus, Plus } from 'lucide-react';

const products = [
  { name: 'Thép Hòa Phát Phi 12', brand: 'HÒA PHÁT', unit: 'Tấn / Cuộn', price: '16.500.000đ', old: '18.900.000đ', discount: '-15%', type: 'Xây Thô', tone: 'from-slate-700 to-slate-950', icon: '▥' },
  { name: 'Xi măng Hà Tiên PCB40', brand: 'HÀ TIÊN', unit: 'Bao 50kg', price: '89.000đ', old: '98.000đ', discount: '-9%', type: 'Xây Thô', tone: 'from-stone-500 to-stone-800', icon: '◈' },
  { name: 'Gạch Granite 60x60', brand: 'VIGLACERA', unit: 'm² / Thùng', price: '189.000đ', old: '249.000đ', discount: '-24%', type: 'Hoàn Thiện', tone: 'from-orange-200 to-stone-400', icon: '▧' },
  { name: 'Sơn nội thất Dulux EasyClean', brand: 'DULUX', unit: 'Thùng 18L', price: '1.245.000đ', old: '1.490.000đ', discount: '-16%', type: 'Hoàn Thiện', tone: 'from-red-700 to-red-950', icon: '●' },
  { name: 'Bồn cầu Toto treo tường', brand: 'TOTO', unit: 'Bộ', price: '6.890.000đ', old: '7.900.000đ', discount: '-13%', type: 'Thiết Bị', tone: 'from-sky-100 to-slate-300', icon: '○' },
  { name: 'Dây điện Cadivi 2.5mm', brand: 'CADIVI', unit: 'Cuộn 100m', price: '1.180.000đ', old: '1.290.000đ', discount: '-8%', type: 'Thiết Bị', tone: 'from-amber-200 to-amber-500', icon: '〰' },
];
const categories = ['Xây Thô', 'Hoàn Thiện', 'Thiết Bị'];

function SectionTitle({ eyebrow, title, action = 'Xem tất cả' }: { eyebrow: string; title: string; action?: string }) { return <div className="mb-5 flex items-end justify-between gap-4"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.2em] text-[#d92d20]">{eyebrow}</p><h2 className="text-2xl font-black tracking-tight text-[#172a34] md:text-3xl">{title}</h2></div><button className="hidden items-center gap-1 text-sm font-bold text-[#d92d20] sm:flex">{action}<ArrowRight size={16} /></button></div>; }
function ProductVisual({ tone, icon }: { tone: string; icon: string }) { return <div className={`relative flex h-40 items-center justify-center overflow-hidden bg-gradient-to-br ${tone}`}><div className="absolute -right-6 -top-10 size-32 rounded-full border-[18px] border-white/10" /><span className="text-7xl font-black text-white/80 drop-shadow-lg">{icon}</span><span className="absolute bottom-3 left-3 rounded bg-white/90 px-2 py-1 text-[10px] font-black text-[#172a34]">CHÍNH HÃNG</span></div>; }

export default function Home() {
  const [cart, setCart] = useState(3); const [category, setCategory] = useState('Xây Thô'); const [estimate, setEstimate] = useState<string | null>(null); const [slide, setSlide] = useState(0);
  const shownProducts = useMemo(() => products.filter((p) => p.type === category || (category === 'Thiết Bị' && p.type === 'Thiết Bị')).slice(0, 4), [category]);
  const addToCart = () => setCart((value) => value + 1);
  const calculate = (form: HTMLFormElement) => { const data = new FormData(form); const area = Number(data.get('area')) || 0; const floors = Number(data.get('floors')) || 1; setEstimate(area ? `Dự toán tham khảo: ${(area * floors * 2850000).toLocaleString('vi-VN')}đ` : 'Vui lòng nhập diện tích để tính dự toán.'); };
  return <div className="min-h-screen bg-[#f5f7f8]">
    <div className="bg-[#172a34] text-[11px] text-white/75"><div className="container-wide flex min-h-10 items-center justify-between gap-3"><div className="flex gap-5"><span className="font-bold text-white">HOTLINE 1900-XXXX</span><span className="hidden sm:inline">Showroom & kho hàng</span><span className="hidden md:inline">Dành cho Nhà thầu & Công trình</span></div><div className="hidden gap-5 sm:flex"><span>Tra cứu đơn hàng</span><span>Bảng giá hôm nay</span><span className="font-bold text-[#f58220]">Đăng nhập / Đăng ký</span></div></div></div>
    <header className="border-b border-slate-200 bg-white"><div className="container-wide flex flex-wrap items-center gap-4 py-4"><div className="mr-auto min-w-[180px]"><div className="text-2xl font-black tracking-tighter text-[#172a34]">VLXD <span className="text-[#172a34]">PRO</span></div><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Vật liệu xây dựng & công trình</div></div><div className="order-3 flex w-full items-center rounded-lg border-2 border-[#e2e8ec] focus-within:border-[#f58220] bg-white md:order-none md:w-[45%]"><input className="min-w-0 flex-1 px-4 py-3 text-sm outline-none" placeholder="Tìm gạch, xi măng, sắt thép, mã sơn..." aria-label="Tìm kiếm sản phẩm" /><button className="flex items-center gap-2 bg-[#f58220] px-4 py-3 font-bold text-white hover:bg-[#dd6f10]"><Search size={17} />Tìm</button></div><div className="flex items-center gap-2"><button className="hidden items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-left text-xs font-bold text-[#172a34] lg:flex"><FileText size={19} className="text-[#d92d20]" />Yêu cầu<br />Báo giá Sỉ</button><button className="relative flex items-center gap-2 rounded-lg bg-[#f58220] px-3 py-3 text-sm font-black text-white" aria-label="Giỏ hàng"><ShoppingCart size={20} /><span className="hidden sm:inline">Giỏ hàng</span><b className="absolute -right-2 -top-2 flex size-5 items-center justify-center rounded-full bg-[#d92d20] text-[10px]">{cart}</b></button></div></div></header>
    <nav className="bg-white shadow-sm"><div className="container-wide flex items-center gap-7 overflow-x-auto whitespace-nowrap py-3 text-sm font-bold"><span className="text-[#d92d20]">Danh mục sản phẩm</span>{['VLXD Thô','VLXD Hoàn Thiện','Điện - Nước','Sơn & Thạch Cao','Dự toán Căn Hộ'].map((item) => <a key={item} href="#products" className="text-slate-600 hover:text-[#d92d20]">{item}</a>)}<span className="ml-auto hidden items-center gap-1 text-xs text-slate-500 lg:flex"><Truck size={16} />Giao hàng toàn quốc</span></div></nav>
    <main className="container-wide py-6">
      <section className="grid gap-4 lg:grid-cols-[2.2fr_1fr]"><div className="relative min-h-[310px] overflow-hidden rounded-2xl bg-[#223d49] p-7 text-white md:p-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_100%,rgba(255,143,0,.65),transparent_42%)]" /><div className="relative max-w-xl"><p className="mb-4 text-xs font-black uppercase tracking-[.25em] text-[#f58220]">{slide === 0 ? 'Ưu đãi nhà thầu tháng này' : 'Nguồn hàng công trình sẵn kho'}</p><h1 className="max-w-lg text-4xl font-black leading-[.95] tracking-tight md:text-6xl">{slide === 0 ? <>Chiết khấu sỉ<br /><span className="text-[#f58220]">đến 20%</span></> : <>Đặt hàng nhanh.<br /><span className="text-[#f58220]">Giao tận chân.</span></>}</h1><p className="mt-5 max-w-sm text-sm text-white/75">Giá tốt trực tiếp từ kho, đầy đủ CO/CQ, phục vụ mọi quy mô công trình.</p><button className="mt-7 flex items-center gap-2 rounded-lg bg-[#f58220] px-5 py-3 text-sm font-black text-white">Nhận báo giá sỉ <ArrowRight size={17} /></button></div><div className="absolute bottom-5 right-7 flex gap-2">{[0,1].map((i) => <button key={i} onClick={() => setSlide(i)} className={`size-2 rounded-full ${slide === i ? 'bg-[#f58220]' : 'bg-white/40'}`} aria-label={`Chuyển banner ${i + 1}`} />)}</div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-2xl bg-[#e9eef0] p-6"><Truck className="mb-7 text-[#d92d20]" size={32} /><h3 className="text-xl font-black">Xe cẩu tận chân<br />công trình</h3><p className="mt-2 text-sm text-slate-600">Phục vụ giao hàng linh hoạt theo tiến độ.</p></div><div className="rounded-2xl bg-[#f58220] p-6 text-white"><ShieldCheck className="mb-7" size={32} /><h3 className="text-xl font-black">Gạch nguyên kiện.<br />Cam kết không vỡ nát.</h3><p className="mt-2 text-sm text-white/80">Đổi trả 100% nếu hư hỏng do vận chuyển.</p></div></div></section>
      <section className="my-7 overflow-hidden rounded-2xl bg-[#172a34] text-white card-shadow"><div className="grid items-center gap-6 p-6 md:grid-cols-[1.3fr_2fr_1fr] md:p-7"><div><div className="mb-2 flex items-center gap-2 text-[#f58220]"><Calculator size={19} /><span className="text-xs font-black uppercase tracking-wider">Công cụ thông minh</span></div><h2 className="text-2xl font-black">Dự toán chi phí &<br />vật liệu tự động</h2></div><form onSubmit={(event) => { event.preventDefault(); calculate(event.currentTarget); }} className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold text-white/70">Loại công trình<select name="type" className="mt-2 w-full rounded-lg border-0 bg-white/10 px-3 py-3 text-sm text-white outline-none"><option className="text-slate-800">Nhà phố</option><option className="text-slate-800">Biệt thự</option></select></label><label className="text-xs font-bold text-white/70">Diện tích m²<input name="area" type="number" className="mt-2 w-full rounded-lg border-0 bg-white/10 px-3 py-3 text-sm text-white outline-none" placeholder="120" /></label><label className="text-xs font-bold text-white/70">Số tầng<input name="floors" type="number" className="mt-2 w-full rounded-lg border-0 bg-white/10 px-3 py-3 text-sm text-white outline-none" placeholder="3" /></label></form><div><button onClick={() => document.querySelector('form')?.requestSubmit()} className="w-full rounded-lg bg-[#f58220] px-4 py-3 text-sm font-black text-white hover:bg-[#ffa726]">TÍNH DỰ TOÁN <span className="hidden sm:inline">& XUẤT BÁO GIÁ</span></button>{estimate && <p className="mt-2 text-xs font-bold text-[#f58220]">{estimate}</p>}</div></div></section>
      <section className="rounded-2xl bg-[#d92d20] p-5 text-white md:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#ffcf70]">Giá tốt theo khối lượng</p><h2 className="text-2xl font-black">XẢ KHO CÔNG TRÌNH</h2></div><div className="rounded-lg bg-[#223d49] px-4 py-2 text-center"><span className="block text-[10px] uppercase text-white/60">Kết thúc trong</span><b className="font-mono text-xl">05:12:45</b></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map((p) => <div key={p.name} className="rounded-xl border border-[#e2e8ec] bg-white p-2 text-[#172a34] shadow-sm"><ProductVisual tone={p.tone} icon={p.icon} /><div className="p-3"><div className="flex justify-between gap-2"><h3 className="text-sm font-black">{p.name}</h3><span className="h-fit rounded bg-[#f58220] px-1.5 py-1 text-[10px] font-black text-white">{p.discount}</span></div><p className="mt-1 text-xs text-slate-500">{p.unit}</p><p className="mt-3 text-lg font-black text-[#d92d20]">{p.price}</p><p className="text-xs text-slate-400 line-through">{p.old}</p><div className="mt-3 h-1.5 rounded-full bg-slate-200"><div className="h-full w-4/5 rounded-full bg-[#f58220]" /></div><p className="mt-1 text-[10px] text-slate-500">Đã bán 80%</p><button onClick={addToCart} className="mt-3 w-full rounded-lg bg-[#172a34] py-2 text-xs font-black text-white">Mua giá sỉ</button></div></div>)}</div></section>
      <div className="my-7 flex flex-wrap items-center justify-center gap-x-10 gap-y-3 rounded-xl border border-slate-200 bg-white px-5 py-4 text-sm"><span className="font-black text-[#172a34]">GIÁ THỊ TRƯỜNG</span><span><b>Thép Hòa Phát</b> <TrendingUp size={15} className="inline text-emerald-600" /> <i className="text-emerald-600">+1%</i></span><span><b>Xi măng Hà Tiên</b> <Minus size={15} className="inline text-slate-400" /> Giữ giá</span><span><b>Cát san lấp</b> <TrendingUp size={15} className="inline rotate-180 text-[#d92d20]" /> <i className="text-[#d92d20]">-0.5%</i></span></div>
      <section id="products"><SectionTitle eyebrow="Danh mục vật liệu" title="Sản phẩm nổi bật" /><div className="mb-5 flex gap-2 overflow-x-auto border-b border-slate-200">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-black ${category === item ? 'border-[#d92d20] text-[#d92d20]' : 'border-transparent text-slate-500'}`}>{item}</button>)}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{shownProducts.map((p) => <article key={p.name} className="overflow-hidden rounded-xl border border-[#e2e8ec] bg-white card-shadow"><ProductVisual tone={p.tone} icon={p.icon} /><div className="p-4"><div className="mb-2 flex items-center justify-between"><span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-black text-slate-600">{p.brand}</span><span className="text-xs text-slate-500">{p.unit}</span></div><h3 className="min-h-10 font-black leading-tight">{p.name}</h3><p className="mt-3 text-xl font-black text-[#d92d20]">{p.price}</p><p className="text-xs text-slate-400">Giá lẻ tham khảo: <span className="line-through">{p.old}</span></p><div className="mt-4 grid grid-cols-2 gap-2"><button className="rounded-lg border border-[#d92d20] py-2 text-xs font-black text-[#d92d20]">Báo giá</button><button onClick={addToCart} className="rounded-lg bg-[#d92d20] py-2 text-xs font-black text-white">Thêm giỏ</button></div></div></article>)}</div></section>
      <section className="my-10"><SectionTitle eyebrow="Giải pháp trọn gói" title="Gói combo công trình" action="Khám phá tất cả" /><div className="grid gap-4 md:grid-cols-3">{[['Combo Xây Thô Tiêu Chuẩn','Nền móng • Thép • Xi măng','Tiết kiệm đến 8%'],['Combo Thiết Bị Phòng Tắm','Bồn cầu • Sen vòi • Lavabo','Tiết kiệm đến 12%'],['Combo Sơn Trọn Gói','Sơn lót • Sơn phủ • Dụng cụ','Tiết kiệm đến 15%']].map(([name, items, saving], i) => <div key={name} className={`rounded-2xl p-6 ${i === 1 ? 'bg-[#172a34] text-white' : 'bg-white'} card-shadow`}><div className="mb-5 flex size-11 items-center justify-center rounded-xl bg-[#f58220] text-white"><ClipboardList /></div><h3 className="text-xl font-black">{name}</h3><p className="mt-2 text-sm opacity-70">{items}</p><ul className="my-5 flex flex-col gap-2 text-sm"><li className="flex items-center gap-2"><Check size={16} className="text-[#f58220]" />Tư vấn theo bản vẽ</li><li className="flex items-center gap-2"><Check size={16} className="text-[#f58220]" />Giao hàng đồng bộ</li></ul><div className="flex items-center justify-between border-t border-current/10 pt-4"><span className="text-sm font-bold text-[#d92d20]">{saving}</span><button className="flex items-center gap-1 text-sm font-black">Mua trọn bộ <ChevronRight size={16} /></button></div></div>)}</div></section>
      <section className="grid gap-3 rounded-2xl bg-[#e9eef0] p-6 sm:grid-cols-2 lg:grid-cols-4">{[[Truck,'Xe cẩu tận công trình','Đúng tiến độ'],[ShieldCheck,'Chứng chỉ CO/CQ','Hàng chính hãng'],[RotateCcw,'Đổi trả 100%','Nếu vỡ nát'],[CreditCard,'Thanh toán linh hoạt','Theo đợt / công nợ']].map(([Icon, title, desc]) => <div key={title as string} className="flex items-center gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-full bg-white text-[#d92d20]"><Icon /></div><div><p className="font-black">{title as string}</p><p className="text-xs text-slate-500">{desc as string}</p></div></div>)}</section>
    </main>
    <footer className="mt-10 bg-[#172a34] py-10 text-white"><div className="container-wide grid gap-8 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><div className="text-2xl font-black text-[#f58220]">VLXD PRO</div><p className="mt-3 text-white/60">Nền tảng vật liệu xây dựng chuyên nghiệp cho mọi công trình Việt Nam.</p><p className="mt-4 text-xs text-white/50">MST: 0312 345 678</p></div><div><h3 className="mb-4 font-black text-[#f58220]">Kho hàng & showroom</h3><p className="text-white/60">Quận 9, TP. Hồ Chí Minh</p><p className="mt-2 text-white/60">Long Biên, Hà Nội</p><p className="mt-2 text-white/60">Bình Dương • Đà Nẵng</p></div><div><h3 className="mb-4 font-black text-[#f58220]">Chính sách nhà thầu</h3><p className="text-white/60">Chính sách công nợ</p><p className="mt-2 text-white/60">Vận chuyển & đổi trả</p><p className="mt-2 text-white/60">Hướng dẫn đặt hàng</p></div><div><h3 className="mb-4 font-black text-[#f58220]">Hỗ trợ khách hàng</h3><p className="text-2xl font-black">1900-XXXX</p><p className="mt-2 text-white/60">Tư vấn 8:00 — 21:00 mỗi ngày</p><div className="mt-5 flex gap-2"><span className="rounded border border-white/20 px-3 py-2 text-xs font-bold">ĐÃ ĐĂNG KÝ BỘ CÔNG THƯƠNG</span></div></div></div><div className="container-wide mt-8 border-t border-white/10 pt-5 text-xs text-white/40">© 2025 VLXD PRO. All rights reserved.</div></footer>
  </div>;
}
